version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

executors:
  docker-executor:
    docker:
      - image: circleci/node:16.10

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Installing dependencies...
          command: npm install

  test:
    executor: docker-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Running tests...
          command: npm run test

  build-and-push:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: xxnlxzx/assignment4.5
          tag: '${CIRCLE_TAG}'
      - docker/push:
          image: xxnlxzx/assignment4.5
          tag: '${CIRCLE_TAG}'

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Deploying application
          command: |
            echo "Deploying version ${CIRCLE_TAG} to production..."
            ./deploy.sh "${CIRCLE_TAG}"

workflows:
  version: 2
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test:
          filters:
            branches:
              only:
                - main
          requires:
            - build
      - build-and-push:
          filters:
            tags:
              only: /^v.*$/  # Match tags starting with "v"
            branches:
              ignore:
                - main
          requires:
            - test
      - deploy:
          filters:
            tags:
              only: /^v.*$/  # Match tags starting with "v"
            branches:
              ignore:
                - main
          requires:
            - build-and-push
