version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
    only:
      - main

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
    only:
      - main
    requires:
      - build

  build-and-push:
    executor: docker/docker
    parameters:
      tag:
        type: string
        default: "0.1.0"
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: xxnlxzx/assignment4.5
          tag: << parameters.tag >>
    only:
      - /^v.*/
    filters:
      tags:
        only: /^v.*/
      
  deploy:
    executor: docker/docker
    parameters:
      tag:
        type: string
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/pull:
          image: xxnlxzx/assignment4.5
          tag: << parameters.tag >>
      - docker/run:
          image: xxnlxzx/assignment4.5
          tag: << parameters.tag >>
          command: deploy.sh
    only:
      - /^v.*/
    filters:
      tags:
        only: /^v.*/

workflows:
  version: 2
  simple_workflow:
    jobs:
      - build
      - test
      - build-and-push:
          parameters:
            tag: "0.1.0"
          requires:
            - test
      - deploy:
          parameters:
            tag: "0.1.0"
          requires:
            - build-and-push
