version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

jobs:
  build:
    filters:
      branches:
        only:
          - main
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Installing dependencies...
          command: npm install

  test:
    filters:
      branches:
        only:
          - main
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Running tests...
          command: npm run test

  build-and-push:
    filters:
      tags:
        only: /.*/
      branches:
        ignore:
          - /^main$/
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: xxnlxzx/assignment4.5
          tag: '${CIRCLE_TAG}'
      - docker/push:
          image: xxnlxzx/assignment4.5
          tag: '${CIRCLE_TAG}'

  deploy:
    filters:
      tags:
        only: /.*/
      branches:
        ignore:
          - /^main$/
    steps:
      - checkout
      - run:
          name: Deploying application
          command: |
            echo "Deploying version ${CIRCLE_TAG} to production..."
            ./deploy.sh "${CIRCLE_TAG}"

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
      - deploy:
          requires:
            - build-and-push
