version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install dependencies
          command: npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test

  build-and-push:
    executor: docker/docker
    parameters:
      tag:
        type: string
        default: "0.1.0"
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: xxnlxzx/assignment4.5
          tag: << pipeline.git.tag >>
      - docker/push:
          image: xxnlxzx/assignment4.5
          tag: << pipeline.git.tag >>

  deploy:
    executor: docker/docker
    parameters:
      tag:
        type: string
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/pull:
          image: xxnlxzx/assignment4.5
          tag: << pipeline.git.tag >>
      - docker/run:
          image: xxnlxzx/assignment4.5
          tag: << pipeline.git.tag >>
          command: deploy.sh

workflows:
  version: 2
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - build-and-push
          filters:
            tags:
              only: /^v.*/
    filters:
      branches:
        only: main
