version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@1.2.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  publish:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build and push Docker image
          command: |
            echo "Logging in to Docker Hub..."
            echo "181287A@n" | docker login -u "xxnlxzx" --password-stdin
            echo "Building Docker image..."
            docker build -t xxnlxzx/assignment4.4:initial .
            echo "Tagging Docker image..."
            docker tag xxnlxzx/assignment4.4:initial xxnlxzx/assignment4.4:version1
            echo "Pushing Docker image..."
            docker push xxnlxzx/assignment4.4:version1

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test

